name: unit test

on:
  pull_request:
    branches:
      - main
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12.4'
          - '3.13'
          - '3.14'

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Poetry
      uses: Gr1N/setup-poetry@v8
      with:
        poetry-version: 1.8.3

    - name: Disables creation of virtualenvs
      run: poetry config virtualenvs.create false

    - name: Install dependencies
      run: poetry install

    - name: run lint
      run: |
        make check
    - name: run tests
      run: |
        make test
